### ISSUE TITLE
Up and down arrow navigation doesn't work correctly

### ISSUE THREAD

**Issue by MSBack** [trey-wallis/obsidian-notion-like-tables#485]
### Describe the bug

When I press arrow down, it navigates diagonally down to the right.
When I press arrow up, it navigates diagonally up to the left.

Left and right works as expected.

### Steps to reproduce

1. Click a cell to begin editing.
2. Press escape to exit editing and mark the current cell.
3. Press up or down.
4. The selection navigates diagonally.

### Expected behavior

I would expect up arrow to navigate up and down arrow to navigate down.

### Are you using the mobile app?

No

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.3.4
	Installer version: v1.2.8
	Operating system: Windows 10 Home 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: deeper work v1.0.3
	Snippets enabled: 11
	Restricted mode: off
	Plugins installed: 106
	Plugins enabled: 92
	
I reproduced this in a test vault, so plugins are irrelevant.

**Comment by trey-wallis** [comment]
@MSBack I just ran into this myself. Do you have multiple table files open? If so, try closing all expect one.

**Comment by MSBack** [comment]
> Do you have multiple table files open? If so, try closing all except one.

No, it happens with only one open. But strangely, I just found out that it only happens in one of my two tables. The other one behaves as expected.

**Comment by trey-wallis** [comment]
Ah, the issue has arose because of the row drag button being placed on the left side instead of the right. I will push out a fix shortly.

**Comment by trey-wallis** [comment]
@MSBack Fixed in 6.11.2

**Comment by MSBack** [comment]
> @MSBack Fixed in 6.11.2

@trey-wallis Unfortunately, the issue persists for me in one of my tables.

I've attached the table in question here. I changed the extension to `.md` to be able to attach it, so you need to change it back to `.table`.
[Predictor table - copy.md](https://github.com/trey-wallis/obsidian-notion-like-tables/files/11618762/Predictor.table.-.copy.md)

**Comment by MSBack** [comment]
Here's a screen-recording made on version 6.11.5:

![Obsidian_xWiIm5Ls0X](https://github.com/trey-wallis/obsidian-notion-like-tables/assets/33608083/852e9a11-99b2-4709-974e-26529f218730)

**Comment by trey-wallis** [comment]
Are you sorting as well?

**Comment by trey-wallis** [comment]
Thanks for sending the table file. Let me try it out

**Comment by MSBack** [comment]
> @MSBack That's odd. Do you have any other tables open?

No, only one.

**Comment by MSBack** [comment]
> Thanks for sending the table file. Let me try it out

Can you reproduce it?

**Comment by trey-wallis** [comment]
Yes, I was able to reproduce it.

**Comment by trey-wallis** [comment]
The issue is that there is a filtered column. I have not taken this into account. I will push out a fix shortly. As well as a new file type :)

**Comment by MSBack** [comment]
> I will push out a fix shortly. As well as a new cell type :)

Great, glad I could help, and looking forward to the new cell type!

**Comment by trey-wallis** [comment]
@MSBack Pushed out in 6.12.0

**Comment by MSBack** [comment]
Great, it works now!
